import { makeStyles } from '@mui/styles'

const useStyles = makeStyles((theme) => ({
  root: {
    width: (props) => (props.width ? props.width : props?.isOpen ? 'calc(100vw - 475px)' : 'calc(100vw - 160px)'),
    position: 'relative',
    margin: 'auto',
  },
  wrapper: {
    width: '100%',
    overflowX: (props) => (props.disableScroll ? 'hidden' : 'auto'),
    overflowY: 'hidden',
    '&::-webkit-scrollbar': {
      background: 'transparent',
      height: 6,
    },
    '&::-webkit-scrollbar-thumb': {
      background: theme.palette.gray[200],
      height: 5,
      margin: 0,
    },
  },
  table: {
    width: '100%',
    borderSpacing: 0,
    position: 'relative',
    padding: ({ totalData, blueTotalData }) => (totalData && !blueTotalData ? '0 10px' : 0),
  },
  visibleOverflow: {
    overflow: 'visible',
  },
  hiddenOverflow: {
    overflow: 'hidden',
  },
  thead: {
    whiteSpace: 'nowrap',
    position: 'relative',
    '&::before': {
      content: '""',
      position: 'absolute',
      bottom: '-2px',
      height: 2,
      backgroundColor: theme.palette.gray[200],
      width: '100%',
      left: 0,
      zIndex: 6,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 0,
      height: 2,
      backgroundColor: theme.palette.gray[200],
      width: '100%',
      left: 0,
      zIndex: 6,
    },
    '& th': {
      padding: '0',
      lineHeight: '24px',
      background: theme.palette.background.default,
      zIndex: 5,
    },
    '& th > div': {
      position: 'relative',
    },
    '& th > div::before': {
      content: '',
      position: 'absolute',
      top: 0,
      left: 0,
      height: 18,
      width: 18,
    },
  },
  th: {
    margin: 0,
    padding: '16px 15px',
    fontSize: 16,
    fontWeight: 600,
    lineHeight: '19px',
    color: ({ darkHeaderTitle }) => theme.palette.gray[darkHeaderTitle ? 600 : 400],
    fontFamily: theme.fontFamily.inter,
    textAlign: 'left',
  },
  tbody: {
    borderBottom: `2px solid ${theme.palette.gray[200]}`,
  },
  tr: {
    '&:nth-child(even) > td': {
      backgroundColor: theme.palette.gray[50],
    },
    '&:nth-child(odd) > td': {
      backgroundColor: theme.palette.background.default,
    },
  },
  td: {
    padding: '0 15px',
    fontSize: 16,
    fontWeight: 600,
    lineHeight: '19px',
    color: theme.palette.gray[600],
    fontFamily: theme.fontFamily.inter,
    margin: '0px important',
    '&:last-child': {
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
    },
    '&:first-child': {
      borderTopLeftRadius: 16,
      borderBottomLeftRadius: 16,
    },
    '& > div': {
      minHeight: 56,
      display: 'flex',
      height: '100%',
      alignItems: 'center',
    },
  },
  sortable_header: {
    zIndex: 101,
    background: theme.palette.background.default,
    boxShadow: theme.boxShadow['16-8'],
    borderRadius: 16,
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    '& > div': {
      display: 'flex',
      alignItems: 'center',
      height: '100%',
    },
    '& p': {
      color: theme.palette.gray[600],
      whiteSpace: 'wrap',
    },
    '& .drag-drop-icon': {
      display: 'flex !important',
      alignItems: 'center',
      marginRight: '4px',
    },
    '& .trash-icon': {
      display: 'none',
    },
    '& .grouped_ball, & .sort_arrow': {
      display: 'none',
    },
  },
  sortable_header_out: {
    '& .trash-icon': {
      display: 'flex !important',
      alignItems: 'center',
      marginRight: '4px',
    },
    '& .drag-drop-icon': {
      display: 'none !important',
    },
  },
  checkbox: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    '& input': {
      width: 14,
      height: 18,
    },
  },
  spacer: {
    height: '16px',
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingTop: 16,
    borderTop: `2px solid ${theme.palette.gray[200]}`,
  },
  pagination: {
    flex: '0 0 30%',
    display: 'flex',
    alignItems: 'center',
  },
  arrowBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    marginRight: 4,
    border: 'none',
    outline: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    '& svg': {
      fill: theme.palette.red[500],
    },
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 40,
    height: 40,
    padding: 4,
    marginRight: 4,
    border: `1px solid transparent`,
    outline: 'none',
    backgroundColor: 'transparent',
    color: theme.palette.gray[600],
    fontSize: 16,
    lineHeight: '19px',
    fontFamily: theme.fontFamily.inter,
    fontWeight: 600,
    cursor: 'pointer',
    '&[disabled]': {
      cursor: 'default',
      border: `1px solid ${theme.palette.gray[300]}`,
      borderRadius: 16,
    },
  },
  dots: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    marginRight: 4,
    border: 'none',
    outline: 'none',
    backgroundColor: 'transparent',
    color: theme.palette.gray[600],
    fontSize: 16,
    lineHeight: '19px',
    fontFamily: theme.fontFamily.inter,
    fontWeight: 600,
    cursor: 'default',
  },
  rich_column_root: {
    userSelect: 'none',
    position: 'relative',
    maxWidth: '100%',
    '&:hover': {
      background: theme.palette.gray[100],
    },
    '&:hover > div:nth-child(1) > div': {
      color: theme.palette.gray[600],
    },
    '&:hover .column-ham': {
      opacity: 1,
      pointerEvents: 'all',
    },
    '& .drag-drop-icon': {
      display: 'none',
    },
    '& .trash-icon': {
      display: 'none',
    },
    '& > div:nth-child(1)': {
      height: 56,
      padding: '0 16px',
      maxWidth: '100%',
    },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 16,
  },
  rich_column_inner: {
    color: ({ isBeingSorted }) => theme.palette.gray[isBeingSorted ? 600 : 400],
    transition: '0.2s',
    flexGrow: 1,
    maxWidth: '100%',
    height: '100%',
  },
  rich_column_menu: {
    opacity: 0,
    minWidth: 18,
    height: 'auto',
    pointerEvents: 'none',
    padding: 2,
    margin: 2,
    cursor: 'pointer',
  },
  rich_column_arrow: {
    transform: ({ decending }) => `rotate(${decending ? 0 : 180}deg)`,
    fill: ({ isBeingSorted }) => (isBeingSorted ? theme.palette.red[500] : undefined),
    marginLeft: 4,
    width: 14,
    opacity: ({ isBeingSorted }) => (isBeingSorted ? 1 : 0),
    minWidth: 14,
  },
  rich_column_resizer: {
    display: 'inline-block',
    background: 'transparent',
    width: 5,
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    transform: 'translateX(50%)',
    zIndex: 1,
    touchAction: 'none',
  },
  rich_column_grouped: {
    display: 'inline-block',
    width: 6,
    height: 6,
    minWidth: 6,
    minHeight: 6,
    background: theme.palette.red[500],
    borderRadius: '50%',
    marginRight: 6,
  },
}))
export default useStyles
