networks:
  magnit:
    external: true

services:
  app:
    image: ${APP_IMAGE:-ghcr.io/nagaimatsuge/magnit-pos:dev-latest}
    container_name: pos-frontend
    env_file: .env.dev
    restart: unless-stopped
    networks:
      - magnit
