networks:
  magnit:
    external: true

services:
  app:
    image: ${APP_IMAGE:-ghcr.io/nagaimatsuge/magnit-pos:latest}
    container_name: pos-frontend
    env_file: .env.production
    restart: unless-stopped
    networks:
      - magnit
