import { makeStyles } from '@mui/styles'

export const useStyles = makeStyles((theme) => ({
  root: {
    marginTop: 16,
  },
  drawer: {
    '& .MuiDrawer-paper': {
      width: 384,
      padding: '64px 32px',
      borderRadius: '64px 0 0 64px',
    },
  },
  title: {
    fontSize: 24,
    lineHeight: '28px',
    fontFamily: theme.fontFamily.gilroyBold,
  },
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: '100%',
  },
  product: {
    display: 'flex',
    width: '100%',
  },
  image: {
    width: 48,
    height: 48,
    border: `1px solid ${theme.palette.gray[200]}`,
    borderRadius: 16,
    overflow: 'hidden',
    '& img': {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
    },
  },
  info: {
    flex: '1 0 50%',
    marginLeft: 8,
  },
  price: {
    display: 'inline-block',
    marginTop: 8,
    fontSize: 16,
    lineHeight: '19px',
    fontWeight: 600,
    color: theme.palette.blue[500],
  },
  percent: {
    flex: '1 0 10%',
    display: 'flex',
    whiteSpace: 'nowrap',
    alignItems: 'center',
    justifyContent: 'center',
    height: 33,
    width: 100,
    marginBottom: 8,
    marginRight: 8,
    padding: 0,
    borderRadius: 16,
    background: theme.palette.gray[100],
    fontWeight: 600,
    color: theme.palette.gray[600],
    cursor: 'pointer',
  },
  actions: {
    position: 'absolute',
    bottom: 64,
    width: 320,
    backgroundColor: 'transparent',
  },
  link: {
    background: 'transparent',
    border: 0,
    outline: 0,
    cursor: 'pointer',
    color: theme.palette.blue[500],
    fontWeight: 600,
    fontSize: 16,
    lineHeight: '19px',
    display: 'inline',
    '&:hover': {
      color: theme.palette.blue[500],
      textDecoration: 'underline',
    },
  },
  sendAgain: {
    '& .MuiTypography-root': {
      color: theme.palette.gray[400],
      lineHeight: '19px',
      fontWeight: 600,
      fontSize: 16,
      fontFamily: theme.fontFamily.inter,
    },
    '& mark': {
      backgroundColor: 'transparent',
      color: theme.palette.blue[500],
      cursor: 'pointer',
      '&:hover': {
        textDecoration: 'underline',
      },
    },
  },
  verificationTitle: {
    fontSize: 24,
    lineHeight: '28px',
    color: '#fff',
    fontFamily: theme.fontFamily.gilroyBold,
    marginTop: 32,
    textAlign: 'center',
    marginBottom: 41,
  },
  verificationDesc: {
    fontWeight: 600,
    textAlign: 'center',
    color: '#fff',
  },
  whiteButton: {
    background: '#fff',
  },
  box: {
    width: 320,
    height: 96,
    borderRadius: 16,
    backgroundColor: theme.palette.gray[100],
    cursor: 'pointer',
    padding: '28px 21px',
    display: 'flex',
    alignItems: 'center',
  },
  text: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '17px',
    whiteSpace: 'nowrap',
  },
  blue: {
    color: theme.palette.blue[500],
    marginBottom: 4,
  },
  or: {
    textAlign: 'center',
    color: theme.palette.gray[400],
    margin: '16px 0',
  },
  loading: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
}))
