name: Pharma-Frontend CI/CD (PM2)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  SSH_HOST: ${{ secrets.DEV_SSH_HOST_DEV }}
  SSH_USER: ${{ secrets.DEV_SSH_USER_DEV }}
  SSH_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
  PROJECT_DIR: "/home/${{ secrets.DEV_SSH_USER_DEV }}/pharma-frontend"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload project to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          source: "."
          target: "${{ env.PROJECT_DIR }}"

      - name: Run deployment commands on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd ${{ env.PROJECT_DIR }}
            yarn install --frozen-lockfile
            yarn build
            pm2 delete pharma-frontend || true
            pm2 start yarn --name pharma-frontend -- serve -s dist -l 3000
            pm2 save
